### PR TITLE
Filter lcov output by `lcov --remove' subcommand

### PR DESCRIPTION
**Pull request by ktns**
Hi,

I've wrote a patch to exclude some files from reports by  ```lcov --remove``` .

I hope you would like it.

### CODE REVIEW

**Comment by alehaa** [comment]
@ktns Maybe I don't got it right, but I think this patch removes files from the generated lcov file. Wouldn't it be better just don't get it in there, i.e. exclude it from the initial file list?

**Comment by ktns** [comment]
Is there such a way? I think ```geninfo``` and ```lcov``` does not have such an option, and it always dump everything in object files.

**Comment by alehaa** [comment]
`lcov_merge_files` merges the data for all source files. Why not check the source files (`ARGV` in this function) for matching the regex?

**Comment by ktns** [comment]
When you use a header-only library, functions defined in header files are reported even if you don't specify source files in the library, as long as you compile with the library. I think the only way to exclude them from the reports is to filter out the data afterwards.

**Comment by alehaa** [comment]
Ok I see. It's not possible to determine dependent files at compile time - ok it is, CMake does this for dependencies, too - but its way to complicated ;)

I think this PR could be merged. I'll do this soon.

**Pull request merged**
